const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 100000,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descripition: "High quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120000,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      descripition: "High quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 200000,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      descripition: "High quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 175000,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descripition: "High quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 95000,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      descripition: "High quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139000,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      descripition: "High quality product",
    },
  ],
};

export default data;
